[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  'forge-std/=lib/forge-std/src/',
  '@chimera/=lib/chimera/src/'
]
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 100


[invariant]
runs = 1000
